/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tracking_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[55] = {12, 4, 0, 12, 24, 36, 48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[3] = {0, 0, 0};

/* tracking_mpc_expl_vde_forw:(i0[12],i1[12x12],i2[12x4],i3[4],i4[])->(o0[12],o1[12x12],o2[12x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=2.0763637147006943e+01;
  a1=arg[3]? arg[3][0] : 0;
  a1=(a0*a1);
  a2=3.1610208881218727e+00;
  a1=(a1+a2);
  a2=arg[0]? arg[0][6] : 0;
  a3=cos(a2);
  a4=arg[0]? arg[0][7] : 0;
  a5=sin(a4);
  a6=(a3*a5);
  a7=arg[0]? arg[0][8] : 0;
  a8=cos(a7);
  a9=(a6*a8);
  a10=sin(a2);
  a11=sin(a7);
  a12=(a10*a11);
  a9=(a9+a12);
  a12=(a1*a9);
  if (res[0]!=0) res[0][3]=a12;
  a12=(a6*a11);
  a13=(a10*a8);
  a12=(a12-a13);
  a13=(a1*a12);
  if (res[0]!=0) res[0][4]=a13;
  a13=(a1*a3);
  a14=cos(a4);
  a15=(a13*a14);
  a16=9.8059999999999992e+00;
  a15=(a15-a16);
  if (res[0]!=0) res[0][5]=a15;
  a15=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][6]=a15;
  a16=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][7]=a16;
  a17=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][8]=a17;
  a18=-2.5651473451232217e+01;
  a2=(a18*a2);
  a19=-2.5580262532002482e+00;
  a15=(a19*a15);
  a2=(a2+a15);
  a15=1.7524089241776338e+01;
  a20=arg[3]? arg[3][1] : 0;
  a20=(a15*a20);
  a2=(a2+a20);
  if (res[0]!=0) res[0][9]=a2;
  a2=-6.1628637406162163e+01;
  a4=(a2*a4);
  a20=-7.2058744720662347e+00;
  a16=(a20*a16);
  a4=(a4+a16);
  a16=5.1903354910673720e+01;
  a21=arg[3]? arg[3][2] : 0;
  a21=(a16*a21);
  a4=(a4+a21);
  if (res[0]!=0) res[0][10]=a4;
  a4=-1.2544174350349687e+01;
  a7=(a4*a7);
  a21=-1.2945379372787613e-02;
  a17=(a21*a17);
  a7=(a7+a17);
  a17=4.3839961280232046e+01;
  a22=arg[3]? arg[3][3] : 0;
  a22=(a17*a22);
  a7=(a7+a22);
  if (res[0]!=0) res[0][11]=a7;
  a7=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a7;
  a7=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a7;
  a7=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a7;
  a7=arg[1]? arg[1][7] : 0;
  a22=(a14*a7);
  a22=(a3*a22);
  a23=arg[1]? arg[1][6] : 0;
  a24=(a10*a23);
  a25=(a5*a24);
  a22=(a22-a25);
  a25=(a8*a22);
  a26=arg[1]? arg[1][8] : 0;
  a27=(a11*a26);
  a28=(a6*a27);
  a25=(a25-a28);
  a28=(a3*a23);
  a29=(a11*a28);
  a30=(a8*a26);
  a31=(a10*a30);
  a29=(a29+a31);
  a25=(a25+a29);
  a25=(a1*a25);
  if (res[1]!=0) res[1][3]=a25;
  a22=(a11*a22);
  a30=(a6*a30);
  a22=(a22+a30);
  a28=(a8*a28);
  a27=(a10*a27);
  a28=(a28-a27);
  a22=(a22-a28);
  a22=(a1*a22);
  if (res[1]!=0) res[1][4]=a22;
  a24=(a1*a24);
  a24=(a14*a24);
  a22=(a5*a7);
  a22=(a13*a22);
  a24=(a24+a22);
  a24=(-a24);
  if (res[1]!=0) res[1][5]=a24;
  a24=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][6]=a24;
  a22=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][7]=a22;
  a28=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a28;
  a23=(a18*a23);
  a24=(a19*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][9]=a23;
  a7=(a2*a7);
  a22=(a20*a22);
  a7=(a7+a22);
  if (res[1]!=0) res[1][10]=a7;
  a26=(a4*a26);
  a28=(a21*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][11]=a26;
  a26=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][12]=a26;
  a26=arg[1]? arg[1][16] : 0;
  if (res[1]!=0) res[1][13]=a26;
  a26=arg[1]? arg[1][17] : 0;
  if (res[1]!=0) res[1][14]=a26;
  a26=arg[1]? arg[1][19] : 0;
  a28=(a14*a26);
  a28=(a3*a28);
  a7=arg[1]? arg[1][18] : 0;
  a22=(a10*a7);
  a23=(a5*a22);
  a28=(a28-a23);
  a23=(a8*a28);
  a24=arg[1]? arg[1][20] : 0;
  a27=(a11*a24);
  a30=(a6*a27);
  a23=(a23-a30);
  a30=(a3*a7);
  a25=(a11*a30);
  a29=(a8*a24);
  a31=(a10*a29);
  a25=(a25+a31);
  a23=(a23+a25);
  a23=(a1*a23);
  if (res[1]!=0) res[1][15]=a23;
  a28=(a11*a28);
  a29=(a6*a29);
  a28=(a28+a29);
  a30=(a8*a30);
  a27=(a10*a27);
  a30=(a30-a27);
  a28=(a28-a30);
  a28=(a1*a28);
  if (res[1]!=0) res[1][16]=a28;
  a22=(a1*a22);
  a22=(a14*a22);
  a28=(a5*a26);
  a28=(a13*a28);
  a22=(a22+a28);
  a22=(-a22);
  if (res[1]!=0) res[1][17]=a22;
  a22=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a22;
  a28=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][19]=a28;
  a30=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][20]=a30;
  a7=(a18*a7);
  a22=(a19*a22);
  a7=(a7+a22);
  if (res[1]!=0) res[1][21]=a7;
  a26=(a2*a26);
  a28=(a20*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][22]=a26;
  a24=(a4*a24);
  a30=(a21*a30);
  a24=(a24+a30);
  if (res[1]!=0) res[1][23]=a24;
  a24=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a24;
  a24=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][25]=a24;
  a24=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a24;
  a24=arg[1]? arg[1][31] : 0;
  a30=(a14*a24);
  a30=(a3*a30);
  a26=arg[1]? arg[1][30] : 0;
  a28=(a10*a26);
  a7=(a5*a28);
  a30=(a30-a7);
  a7=(a8*a30);
  a22=arg[1]? arg[1][32] : 0;
  a27=(a11*a22);
  a29=(a6*a27);
  a7=(a7-a29);
  a29=(a3*a26);
  a23=(a11*a29);
  a25=(a8*a22);
  a31=(a10*a25);
  a23=(a23+a31);
  a7=(a7+a23);
  a7=(a1*a7);
  if (res[1]!=0) res[1][27]=a7;
  a30=(a11*a30);
  a25=(a6*a25);
  a30=(a30+a25);
  a29=(a8*a29);
  a27=(a10*a27);
  a29=(a29-a27);
  a30=(a30-a29);
  a30=(a1*a30);
  if (res[1]!=0) res[1][28]=a30;
  a28=(a1*a28);
  a28=(a14*a28);
  a30=(a5*a24);
  a30=(a13*a30);
  a28=(a28+a30);
  a28=(-a28);
  if (res[1]!=0) res[1][29]=a28;
  a28=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a28;
  a30=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][31]=a30;
  a29=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][32]=a29;
  a26=(a18*a26);
  a28=(a19*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][33]=a26;
  a24=(a2*a24);
  a30=(a20*a30);
  a24=(a24+a30);
  if (res[1]!=0) res[1][34]=a24;
  a22=(a4*a22);
  a29=(a21*a29);
  a22=(a22+a29);
  if (res[1]!=0) res[1][35]=a22;
  a22=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][36]=a22;
  a22=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a22;
  a22=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][38]=a22;
  a22=arg[1]? arg[1][43] : 0;
  a29=(a14*a22);
  a29=(a3*a29);
  a24=arg[1]? arg[1][42] : 0;
  a30=(a10*a24);
  a26=(a5*a30);
  a29=(a29-a26);
  a26=(a8*a29);
  a28=arg[1]? arg[1][44] : 0;
  a27=(a11*a28);
  a25=(a6*a27);
  a26=(a26-a25);
  a25=(a3*a24);
  a7=(a11*a25);
  a23=(a8*a28);
  a31=(a10*a23);
  a7=(a7+a31);
  a26=(a26+a7);
  a26=(a1*a26);
  if (res[1]!=0) res[1][39]=a26;
  a29=(a11*a29);
  a23=(a6*a23);
  a29=(a29+a23);
  a25=(a8*a25);
  a27=(a10*a27);
  a25=(a25-a27);
  a29=(a29-a25);
  a29=(a1*a29);
  if (res[1]!=0) res[1][40]=a29;
  a30=(a1*a30);
  a30=(a14*a30);
  a29=(a5*a22);
  a29=(a13*a29);
  a30=(a30+a29);
  a30=(-a30);
  if (res[1]!=0) res[1][41]=a30;
  a30=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][42]=a30;
  a29=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][43]=a29;
  a25=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][44]=a25;
  a24=(a18*a24);
  a30=(a19*a30);
  a24=(a24+a30);
  if (res[1]!=0) res[1][45]=a24;
  a22=(a2*a22);
  a29=(a20*a29);
  a22=(a22+a29);
  if (res[1]!=0) res[1][46]=a22;
  a28=(a4*a28);
  a25=(a21*a25);
  a28=(a28+a25);
  if (res[1]!=0) res[1][47]=a28;
  a28=arg[1]? arg[1][51] : 0;
  if (res[1]!=0) res[1][48]=a28;
  a28=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][49]=a28;
  a28=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][50]=a28;
  a28=arg[1]? arg[1][55] : 0;
  a25=(a14*a28);
  a25=(a3*a25);
  a22=arg[1]? arg[1][54] : 0;
  a29=(a10*a22);
  a24=(a5*a29);
  a25=(a25-a24);
  a24=(a8*a25);
  a30=arg[1]? arg[1][56] : 0;
  a27=(a11*a30);
  a23=(a6*a27);
  a24=(a24-a23);
  a23=(a3*a22);
  a26=(a11*a23);
  a7=(a8*a30);
  a31=(a10*a7);
  a26=(a26+a31);
  a24=(a24+a26);
  a24=(a1*a24);
  if (res[1]!=0) res[1][51]=a24;
  a25=(a11*a25);
  a7=(a6*a7);
  a25=(a25+a7);
  a23=(a8*a23);
  a27=(a10*a27);
  a23=(a23-a27);
  a25=(a25-a23);
  a25=(a1*a25);
  if (res[1]!=0) res[1][52]=a25;
  a29=(a1*a29);
  a29=(a14*a29);
  a25=(a5*a28);
  a25=(a13*a25);
  a29=(a29+a25);
  a29=(-a29);
  if (res[1]!=0) res[1][53]=a29;
  a29=arg[1]? arg[1][57] : 0;
  if (res[1]!=0) res[1][54]=a29;
  a25=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][55]=a25;
  a23=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][56]=a23;
  a22=(a18*a22);
  a29=(a19*a29);
  a22=(a22+a29);
  if (res[1]!=0) res[1][57]=a22;
  a28=(a2*a28);
  a25=(a20*a25);
  a28=(a28+a25);
  if (res[1]!=0) res[1][58]=a28;
  a30=(a4*a30);
  a23=(a21*a23);
  a30=(a30+a23);
  if (res[1]!=0) res[1][59]=a30;
  a30=arg[1]? arg[1][63] : 0;
  if (res[1]!=0) res[1][60]=a30;
  a30=arg[1]? arg[1][64] : 0;
  if (res[1]!=0) res[1][61]=a30;
  a30=arg[1]? arg[1][65] : 0;
  if (res[1]!=0) res[1][62]=a30;
  a30=arg[1]? arg[1][67] : 0;
  a23=(a14*a30);
  a23=(a3*a23);
  a28=arg[1]? arg[1][66] : 0;
  a25=(a10*a28);
  a22=(a5*a25);
  a23=(a23-a22);
  a22=(a8*a23);
  a29=arg[1]? arg[1][68] : 0;
  a27=(a11*a29);
  a7=(a6*a27);
  a22=(a22-a7);
  a7=(a3*a28);
  a24=(a11*a7);
  a26=(a8*a29);
  a31=(a10*a26);
  a24=(a24+a31);
  a22=(a22+a24);
  a22=(a1*a22);
  if (res[1]!=0) res[1][63]=a22;
  a23=(a11*a23);
  a26=(a6*a26);
  a23=(a23+a26);
  a7=(a8*a7);
  a27=(a10*a27);
  a7=(a7-a27);
  a23=(a23-a7);
  a23=(a1*a23);
  if (res[1]!=0) res[1][64]=a23;
  a25=(a1*a25);
  a25=(a14*a25);
  a23=(a5*a30);
  a23=(a13*a23);
  a25=(a25+a23);
  a25=(-a25);
  if (res[1]!=0) res[1][65]=a25;
  a25=arg[1]? arg[1][69] : 0;
  if (res[1]!=0) res[1][66]=a25;
  a23=arg[1]? arg[1][70] : 0;
  if (res[1]!=0) res[1][67]=a23;
  a7=arg[1]? arg[1][71] : 0;
  if (res[1]!=0) res[1][68]=a7;
  a28=(a18*a28);
  a25=(a19*a25);
  a28=(a28+a25);
  if (res[1]!=0) res[1][69]=a28;
  a30=(a2*a30);
  a23=(a20*a23);
  a30=(a30+a23);
  if (res[1]!=0) res[1][70]=a30;
  a29=(a4*a29);
  a7=(a21*a7);
  a29=(a29+a7);
  if (res[1]!=0) res[1][71]=a29;
  a29=arg[1]? arg[1][75] : 0;
  if (res[1]!=0) res[1][72]=a29;
  a29=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][73]=a29;
  a29=arg[1]? arg[1][77] : 0;
  if (res[1]!=0) res[1][74]=a29;
  a29=arg[1]? arg[1][79] : 0;
  a7=(a14*a29);
  a7=(a3*a7);
  a30=arg[1]? arg[1][78] : 0;
  a23=(a10*a30);
  a28=(a5*a23);
  a7=(a7-a28);
  a28=(a8*a7);
  a25=arg[1]? arg[1][80] : 0;
  a27=(a11*a25);
  a26=(a6*a27);
  a28=(a28-a26);
  a26=(a3*a30);
  a22=(a11*a26);
  a24=(a8*a25);
  a31=(a10*a24);
  a22=(a22+a31);
  a28=(a28+a22);
  a28=(a1*a28);
  if (res[1]!=0) res[1][75]=a28;
  a7=(a11*a7);
  a24=(a6*a24);
  a7=(a7+a24);
  a26=(a8*a26);
  a27=(a10*a27);
  a26=(a26-a27);
  a7=(a7-a26);
  a7=(a1*a7);
  if (res[1]!=0) res[1][76]=a7;
  a23=(a1*a23);
  a23=(a14*a23);
  a7=(a5*a29);
  a7=(a13*a7);
  a23=(a23+a7);
  a23=(-a23);
  if (res[1]!=0) res[1][77]=a23;
  a23=arg[1]? arg[1][81] : 0;
  if (res[1]!=0) res[1][78]=a23;
  a7=arg[1]? arg[1][82] : 0;
  if (res[1]!=0) res[1][79]=a7;
  a26=arg[1]? arg[1][83] : 0;
  if (res[1]!=0) res[1][80]=a26;
  a30=(a18*a30);
  a23=(a19*a23);
  a30=(a30+a23);
  if (res[1]!=0) res[1][81]=a30;
  a29=(a2*a29);
  a7=(a20*a7);
  a29=(a29+a7);
  if (res[1]!=0) res[1][82]=a29;
  a25=(a4*a25);
  a26=(a21*a26);
  a25=(a25+a26);
  if (res[1]!=0) res[1][83]=a25;
  a25=arg[1]? arg[1][87] : 0;
  if (res[1]!=0) res[1][84]=a25;
  a25=arg[1]? arg[1][88] : 0;
  if (res[1]!=0) res[1][85]=a25;
  a25=arg[1]? arg[1][89] : 0;
  if (res[1]!=0) res[1][86]=a25;
  a25=arg[1]? arg[1][91] : 0;
  a26=(a14*a25);
  a26=(a3*a26);
  a29=arg[1]? arg[1][90] : 0;
  a7=(a10*a29);
  a30=(a5*a7);
  a26=(a26-a30);
  a30=(a8*a26);
  a23=arg[1]? arg[1][92] : 0;
  a27=(a11*a23);
  a24=(a6*a27);
  a30=(a30-a24);
  a24=(a3*a29);
  a28=(a11*a24);
  a22=(a8*a23);
  a31=(a10*a22);
  a28=(a28+a31);
  a30=(a30+a28);
  a30=(a1*a30);
  if (res[1]!=0) res[1][87]=a30;
  a26=(a11*a26);
  a22=(a6*a22);
  a26=(a26+a22);
  a24=(a8*a24);
  a27=(a10*a27);
  a24=(a24-a27);
  a26=(a26-a24);
  a26=(a1*a26);
  if (res[1]!=0) res[1][88]=a26;
  a7=(a1*a7);
  a7=(a14*a7);
  a26=(a5*a25);
  a26=(a13*a26);
  a7=(a7+a26);
  a7=(-a7);
  if (res[1]!=0) res[1][89]=a7;
  a7=arg[1]? arg[1][93] : 0;
  if (res[1]!=0) res[1][90]=a7;
  a26=arg[1]? arg[1][94] : 0;
  if (res[1]!=0) res[1][91]=a26;
  a24=arg[1]? arg[1][95] : 0;
  if (res[1]!=0) res[1][92]=a24;
  a29=(a18*a29);
  a7=(a19*a7);
  a29=(a29+a7);
  if (res[1]!=0) res[1][93]=a29;
  a25=(a2*a25);
  a26=(a20*a26);
  a25=(a25+a26);
  if (res[1]!=0) res[1][94]=a25;
  a23=(a4*a23);
  a24=(a21*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][95]=a23;
  a23=arg[1]? arg[1][99] : 0;
  if (res[1]!=0) res[1][96]=a23;
  a23=arg[1]? arg[1][100] : 0;
  if (res[1]!=0) res[1][97]=a23;
  a23=arg[1]? arg[1][101] : 0;
  if (res[1]!=0) res[1][98]=a23;
  a23=arg[1]? arg[1][103] : 0;
  a24=(a14*a23);
  a24=(a3*a24);
  a25=arg[1]? arg[1][102] : 0;
  a26=(a10*a25);
  a29=(a5*a26);
  a24=(a24-a29);
  a29=(a8*a24);
  a7=arg[1]? arg[1][104] : 0;
  a27=(a11*a7);
  a22=(a6*a27);
  a29=(a29-a22);
  a22=(a3*a25);
  a30=(a11*a22);
  a28=(a8*a7);
  a31=(a10*a28);
  a30=(a30+a31);
  a29=(a29+a30);
  a29=(a1*a29);
  if (res[1]!=0) res[1][99]=a29;
  a24=(a11*a24);
  a28=(a6*a28);
  a24=(a24+a28);
  a22=(a8*a22);
  a27=(a10*a27);
  a22=(a22-a27);
  a24=(a24-a22);
  a24=(a1*a24);
  if (res[1]!=0) res[1][100]=a24;
  a26=(a1*a26);
  a26=(a14*a26);
  a24=(a5*a23);
  a24=(a13*a24);
  a26=(a26+a24);
  a26=(-a26);
  if (res[1]!=0) res[1][101]=a26;
  a26=arg[1]? arg[1][105] : 0;
  if (res[1]!=0) res[1][102]=a26;
  a24=arg[1]? arg[1][106] : 0;
  if (res[1]!=0) res[1][103]=a24;
  a22=arg[1]? arg[1][107] : 0;
  if (res[1]!=0) res[1][104]=a22;
  a25=(a18*a25);
  a26=(a19*a26);
  a25=(a25+a26);
  if (res[1]!=0) res[1][105]=a25;
  a23=(a2*a23);
  a24=(a20*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][106]=a23;
  a7=(a4*a7);
  a22=(a21*a22);
  a7=(a7+a22);
  if (res[1]!=0) res[1][107]=a7;
  a7=arg[1]? arg[1][111] : 0;
  if (res[1]!=0) res[1][108]=a7;
  a7=arg[1]? arg[1][112] : 0;
  if (res[1]!=0) res[1][109]=a7;
  a7=arg[1]? arg[1][113] : 0;
  if (res[1]!=0) res[1][110]=a7;
  a7=arg[1]? arg[1][115] : 0;
  a22=(a14*a7);
  a22=(a3*a22);
  a23=arg[1]? arg[1][114] : 0;
  a24=(a10*a23);
  a25=(a5*a24);
  a22=(a22-a25);
  a25=(a8*a22);
  a26=arg[1]? arg[1][116] : 0;
  a27=(a11*a26);
  a28=(a6*a27);
  a25=(a25-a28);
  a28=(a3*a23);
  a29=(a11*a28);
  a30=(a8*a26);
  a31=(a10*a30);
  a29=(a29+a31);
  a25=(a25+a29);
  a25=(a1*a25);
  if (res[1]!=0) res[1][111]=a25;
  a22=(a11*a22);
  a30=(a6*a30);
  a22=(a22+a30);
  a28=(a8*a28);
  a27=(a10*a27);
  a28=(a28-a27);
  a22=(a22-a28);
  a22=(a1*a22);
  if (res[1]!=0) res[1][112]=a22;
  a24=(a1*a24);
  a24=(a14*a24);
  a22=(a5*a7);
  a22=(a13*a22);
  a24=(a24+a22);
  a24=(-a24);
  if (res[1]!=0) res[1][113]=a24;
  a24=arg[1]? arg[1][117] : 0;
  if (res[1]!=0) res[1][114]=a24;
  a22=arg[1]? arg[1][118] : 0;
  if (res[1]!=0) res[1][115]=a22;
  a28=arg[1]? arg[1][119] : 0;
  if (res[1]!=0) res[1][116]=a28;
  a23=(a18*a23);
  a24=(a19*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][117]=a23;
  a7=(a2*a7);
  a22=(a20*a22);
  a7=(a7+a22);
  if (res[1]!=0) res[1][118]=a7;
  a26=(a4*a26);
  a28=(a21*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][119]=a26;
  a26=arg[1]? arg[1][123] : 0;
  if (res[1]!=0) res[1][120]=a26;
  a26=arg[1]? arg[1][124] : 0;
  if (res[1]!=0) res[1][121]=a26;
  a26=arg[1]? arg[1][125] : 0;
  if (res[1]!=0) res[1][122]=a26;
  a26=arg[1]? arg[1][127] : 0;
  a28=(a14*a26);
  a28=(a3*a28);
  a7=arg[1]? arg[1][126] : 0;
  a22=(a10*a7);
  a23=(a5*a22);
  a28=(a28-a23);
  a23=(a8*a28);
  a24=arg[1]? arg[1][128] : 0;
  a27=(a11*a24);
  a30=(a6*a27);
  a23=(a23-a30);
  a30=(a3*a7);
  a25=(a11*a30);
  a29=(a8*a24);
  a31=(a10*a29);
  a25=(a25+a31);
  a23=(a23+a25);
  a23=(a1*a23);
  if (res[1]!=0) res[1][123]=a23;
  a28=(a11*a28);
  a29=(a6*a29);
  a28=(a28+a29);
  a30=(a8*a30);
  a27=(a10*a27);
  a30=(a30-a27);
  a28=(a28-a30);
  a28=(a1*a28);
  if (res[1]!=0) res[1][124]=a28;
  a22=(a1*a22);
  a22=(a14*a22);
  a28=(a5*a26);
  a28=(a13*a28);
  a22=(a22+a28);
  a22=(-a22);
  if (res[1]!=0) res[1][125]=a22;
  a22=arg[1]? arg[1][129] : 0;
  if (res[1]!=0) res[1][126]=a22;
  a28=arg[1]? arg[1][130] : 0;
  if (res[1]!=0) res[1][127]=a28;
  a30=arg[1]? arg[1][131] : 0;
  if (res[1]!=0) res[1][128]=a30;
  a7=(a18*a7);
  a22=(a19*a22);
  a7=(a7+a22);
  if (res[1]!=0) res[1][129]=a7;
  a26=(a2*a26);
  a28=(a20*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][130]=a26;
  a24=(a4*a24);
  a30=(a21*a30);
  a24=(a24+a30);
  if (res[1]!=0) res[1][131]=a24;
  a24=arg[1]? arg[1][135] : 0;
  if (res[1]!=0) res[1][132]=a24;
  a24=arg[1]? arg[1][136] : 0;
  if (res[1]!=0) res[1][133]=a24;
  a24=arg[1]? arg[1][137] : 0;
  if (res[1]!=0) res[1][134]=a24;
  a24=arg[1]? arg[1][139] : 0;
  a30=(a14*a24);
  a30=(a3*a30);
  a26=arg[1]? arg[1][138] : 0;
  a28=(a10*a26);
  a7=(a5*a28);
  a30=(a30-a7);
  a7=(a8*a30);
  a22=arg[1]? arg[1][140] : 0;
  a27=(a11*a22);
  a29=(a6*a27);
  a7=(a7-a29);
  a29=(a3*a26);
  a23=(a11*a29);
  a25=(a8*a22);
  a31=(a10*a25);
  a23=(a23+a31);
  a7=(a7+a23);
  a7=(a1*a7);
  if (res[1]!=0) res[1][135]=a7;
  a30=(a11*a30);
  a25=(a6*a25);
  a30=(a30+a25);
  a29=(a8*a29);
  a27=(a10*a27);
  a29=(a29-a27);
  a30=(a30-a29);
  a30=(a1*a30);
  if (res[1]!=0) res[1][136]=a30;
  a28=(a1*a28);
  a28=(a14*a28);
  a30=(a5*a24);
  a30=(a13*a30);
  a28=(a28+a30);
  a28=(-a28);
  if (res[1]!=0) res[1][137]=a28;
  a28=arg[1]? arg[1][141] : 0;
  if (res[1]!=0) res[1][138]=a28;
  a30=arg[1]? arg[1][142] : 0;
  if (res[1]!=0) res[1][139]=a30;
  a29=arg[1]? arg[1][143] : 0;
  if (res[1]!=0) res[1][140]=a29;
  a26=(a18*a26);
  a28=(a19*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][141]=a26;
  a24=(a2*a24);
  a30=(a20*a30);
  a24=(a24+a30);
  if (res[1]!=0) res[1][142]=a24;
  a22=(a4*a22);
  a29=(a21*a29);
  a22=(a22+a29);
  if (res[1]!=0) res[1][143]=a22;
  a22=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a22;
  a22=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a22;
  a22=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a22;
  a9=(a0*a9);
  a22=arg[2]? arg[2][7] : 0;
  a29=(a14*a22);
  a29=(a3*a29);
  a24=arg[2]? arg[2][6] : 0;
  a30=(a10*a24);
  a26=(a5*a30);
  a29=(a29-a26);
  a26=(a8*a29);
  a28=arg[2]? arg[2][8] : 0;
  a27=(a11*a28);
  a25=(a6*a27);
  a26=(a26-a25);
  a25=(a3*a24);
  a7=(a11*a25);
  a23=(a8*a28);
  a31=(a10*a23);
  a7=(a7+a31);
  a26=(a26+a7);
  a26=(a1*a26);
  a9=(a9+a26);
  if (res[2]!=0) res[2][3]=a9;
  a12=(a0*a12);
  a29=(a11*a29);
  a23=(a6*a23);
  a29=(a29+a23);
  a25=(a8*a25);
  a27=(a10*a27);
  a25=(a25-a27);
  a29=(a29-a25);
  a29=(a1*a29);
  a12=(a12+a29);
  if (res[2]!=0) res[2][4]=a12;
  a0=(a0*a3);
  a0=(a14*a0);
  a30=(a1*a30);
  a30=(a14*a30);
  a12=(a5*a22);
  a12=(a13*a12);
  a30=(a30+a12);
  a0=(a0-a30);
  if (res[2]!=0) res[2][5]=a0;
  a0=arg[2]? arg[2][9] : 0;
  if (res[2]!=0) res[2][6]=a0;
  a30=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][7]=a30;
  a12=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][8]=a12;
  a24=(a18*a24);
  a0=(a19*a0);
  a24=(a24+a0);
  if (res[2]!=0) res[2][9]=a24;
  a22=(a2*a22);
  a30=(a20*a30);
  a22=(a22+a30);
  if (res[2]!=0) res[2][10]=a22;
  a28=(a4*a28);
  a12=(a21*a12);
  a28=(a28+a12);
  if (res[2]!=0) res[2][11]=a28;
  a28=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][12]=a28;
  a28=arg[2]? arg[2][16] : 0;
  if (res[2]!=0) res[2][13]=a28;
  a28=arg[2]? arg[2][17] : 0;
  if (res[2]!=0) res[2][14]=a28;
  a28=arg[2]? arg[2][19] : 0;
  a12=(a14*a28);
  a12=(a3*a12);
  a22=arg[2]? arg[2][18] : 0;
  a30=(a10*a22);
  a24=(a5*a30);
  a12=(a12-a24);
  a24=(a8*a12);
  a0=arg[2]? arg[2][20] : 0;
  a29=(a11*a0);
  a25=(a6*a29);
  a24=(a24-a25);
  a25=(a3*a22);
  a27=(a11*a25);
  a23=(a8*a0);
  a9=(a10*a23);
  a27=(a27+a9);
  a24=(a24+a27);
  a24=(a1*a24);
  if (res[2]!=0) res[2][15]=a24;
  a12=(a11*a12);
  a23=(a6*a23);
  a12=(a12+a23);
  a25=(a8*a25);
  a29=(a10*a29);
  a25=(a25-a29);
  a12=(a12-a25);
  a12=(a1*a12);
  if (res[2]!=0) res[2][16]=a12;
  a30=(a1*a30);
  a30=(a14*a30);
  a12=(a5*a28);
  a12=(a13*a12);
  a30=(a30+a12);
  a30=(-a30);
  if (res[2]!=0) res[2][17]=a30;
  a30=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a30;
  a12=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][19]=a12;
  a25=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][20]=a25;
  a22=(a18*a22);
  a30=(a19*a30);
  a22=(a22+a30);
  a15=(a15+a22);
  if (res[2]!=0) res[2][21]=a15;
  a28=(a2*a28);
  a12=(a20*a12);
  a28=(a28+a12);
  if (res[2]!=0) res[2][22]=a28;
  a0=(a4*a0);
  a25=(a21*a25);
  a0=(a0+a25);
  if (res[2]!=0) res[2][23]=a0;
  a0=arg[2]? arg[2][27] : 0;
  if (res[2]!=0) res[2][24]=a0;
  a0=arg[2]? arg[2][28] : 0;
  if (res[2]!=0) res[2][25]=a0;
  a0=arg[2]? arg[2][29] : 0;
  if (res[2]!=0) res[2][26]=a0;
  a0=arg[2]? arg[2][31] : 0;
  a25=(a14*a0);
  a25=(a3*a25);
  a28=arg[2]? arg[2][30] : 0;
  a12=(a10*a28);
  a15=(a5*a12);
  a25=(a25-a15);
  a15=(a8*a25);
  a22=arg[2]? arg[2][32] : 0;
  a30=(a11*a22);
  a29=(a6*a30);
  a15=(a15-a29);
  a29=(a3*a28);
  a23=(a11*a29);
  a24=(a8*a22);
  a27=(a10*a24);
  a23=(a23+a27);
  a15=(a15+a23);
  a15=(a1*a15);
  if (res[2]!=0) res[2][27]=a15;
  a25=(a11*a25);
  a24=(a6*a24);
  a25=(a25+a24);
  a29=(a8*a29);
  a30=(a10*a30);
  a29=(a29-a30);
  a25=(a25-a29);
  a25=(a1*a25);
  if (res[2]!=0) res[2][28]=a25;
  a12=(a1*a12);
  a12=(a14*a12);
  a25=(a5*a0);
  a25=(a13*a25);
  a12=(a12+a25);
  a12=(-a12);
  if (res[2]!=0) res[2][29]=a12;
  a12=arg[2]? arg[2][33] : 0;
  if (res[2]!=0) res[2][30]=a12;
  a25=arg[2]? arg[2][34] : 0;
  if (res[2]!=0) res[2][31]=a25;
  a29=arg[2]? arg[2][35] : 0;
  if (res[2]!=0) res[2][32]=a29;
  a28=(a18*a28);
  a12=(a19*a12);
  a28=(a28+a12);
  if (res[2]!=0) res[2][33]=a28;
  a0=(a2*a0);
  a25=(a20*a25);
  a0=(a0+a25);
  a16=(a16+a0);
  if (res[2]!=0) res[2][34]=a16;
  a22=(a4*a22);
  a29=(a21*a29);
  a22=(a22+a29);
  if (res[2]!=0) res[2][35]=a22;
  a22=arg[2]? arg[2][39] : 0;
  if (res[2]!=0) res[2][36]=a22;
  a22=arg[2]? arg[2][40] : 0;
  if (res[2]!=0) res[2][37]=a22;
  a22=arg[2]? arg[2][41] : 0;
  if (res[2]!=0) res[2][38]=a22;
  a22=arg[2]? arg[2][43] : 0;
  a29=(a14*a22);
  a29=(a3*a29);
  a16=arg[2]? arg[2][42] : 0;
  a0=(a10*a16);
  a25=(a5*a0);
  a29=(a29-a25);
  a25=(a8*a29);
  a28=arg[2]? arg[2][44] : 0;
  a12=(a11*a28);
  a30=(a6*a12);
  a25=(a25-a30);
  a3=(a3*a16);
  a30=(a11*a3);
  a24=(a8*a28);
  a15=(a10*a24);
  a30=(a30+a15);
  a25=(a25+a30);
  a25=(a1*a25);
  if (res[2]!=0) res[2][39]=a25;
  a11=(a11*a29);
  a6=(a6*a24);
  a11=(a11+a6);
  a8=(a8*a3);
  a10=(a10*a12);
  a8=(a8-a10);
  a11=(a11-a8);
  a11=(a1*a11);
  if (res[2]!=0) res[2][40]=a11;
  a1=(a1*a0);
  a14=(a14*a1);
  a5=(a5*a22);
  a13=(a13*a5);
  a14=(a14+a13);
  a14=(-a14);
  if (res[2]!=0) res[2][41]=a14;
  a14=arg[2]? arg[2][45] : 0;
  if (res[2]!=0) res[2][42]=a14;
  a13=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][43]=a13;
  a5=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][44]=a5;
  a18=(a18*a16);
  a19=(a19*a14);
  a18=(a18+a19);
  if (res[2]!=0) res[2][45]=a18;
  a2=(a2*a22);
  a20=(a20*a13);
  a2=(a2+a20);
  if (res[2]!=0) res[2][46]=a2;
  a4=(a4*a28);
  a21=(a21*a5);
  a4=(a4+a21);
  a17=(a17+a4);
  if (res[2]!=0) res[2][47]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tracking_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tracking_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tracking_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void tracking_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tracking_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tracking_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tracking_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tracking_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tracking_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tracking_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tracking_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tracking_mpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
